project_name: cloudflare-kubernetes-gateway
builds:
  - skip: true
kos:
  - repository: "ghcr.io/pl4nty/cloudflare-kubernetes-gateway"
    tags:
      - latest
      - "{{ .Tag }}"
    bare: true
    preserve_import_paths: false
    platforms:
      - all
    main: ./cmd
