# SPDX-FileCopyrightText: 2023-2026 Tom Plant, Elias Elwyn, and contributors
# SPDX-License-Identifier: MIT
namespace: cloudflare-gateway
namePrefix: cloudflare-
resources:
- monitor.yaml
- image_monitor.yaml
