name: CI
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: securego/gosec@v2.20.0
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."
      - uses: github/codeql-action/upload-sarif@v3.25.8
        with:
          sarif_file: results.sarif

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: stable

      - uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest
          args: --timeout=10m

      - run: go build -v ./...
      - uses: robherley/go-test-action@v0.4.1

  conformance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Checkout API repo
        uses: actions/checkout@v4.1.6
        with:
          repository: kubernetes-sigs/gateway-api
          ref: v1.1.0
          path: gateway-api
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: stable
      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Deploy controller
        run: |
          kubectl apply -k gateway-api/config/crd
          make deploy
          kubectl create secret -n default generic gateway-conformance \
          --from-literal=ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} \
          --from-literal=TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}
          kubectl apply -f .github/gateway-class.yaml

      - uses: robherley/go-test-action@v0.4.1
        with:
          moduleDirectory: gateway-api
          testArguments: ./conformance -run TestConformance -args --supported-features=Gateway,HTTPRoute --cleanup-base-resources=false

      - name: Get manager logs
        if: ${{ !cancelled() }}
        run: kubectl logs -n cloudflare-gateway deployment/cloudflare-controller-manager > /tmp/manager.log
      - name: Upload manager logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: manager-log
          path: /tmp/manager.log

  release-please:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4.1.1
        id: release
        with:
          release-type: go

  release:
    needs:
      - scan
    if: needs.prep.outputs.releases_created
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: actions/setup-go@v5.0.1
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v6.0.0
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
